# ➡️ Specifies the API version of the Kubernetes object you're defining.
# apps/v1 is the stable version for deployments.
apiVersion: apps/v1

# ➡️ You're defining a Deployment resource — a controller that manages pods and ensures a specified number of them are running.
kind: Deployment

# ➡️ Metadata about this Kubernetes object.
metadata:
  # name: the name of the Deployment.
  # This is used to identify and manage the deployment (e.g., kubectl get deployment kubernetes-learning).
  name: kubernetes-learning

spec:
  # ➡️ The desired number of pod replicas (i.e., containers running your app).
  # Here, Kubernetes will ensure 2 pods are always running.
  replicas: 2
  # ➡️ This tells the Deployment:
  # “Which pods should I manage?”
  selector:
    # It matches pods whose labels include app: kubernetes-learning
    # Think of it like a filter: “Find pods with this label, and I’ll manage them.”
    matchLabels:
      app: kubernetes-learning

  # ➡️ This is the template for each pod created by this Deployment.
  template:
    metadata:
      # The labels here must match the selector above
      labels:
        # Every pod created will be
        app: kubernetes-learning

    # ➡️ Starts the definition of containers that should run inside each pod.
    spec:
     # ✅ Declare volumes
      volumes:
        - name: cfg
          configMap:
            name: kube-learning-config
      serviceAccountName: kubernetes-learning-sa
      # One pod can run multiple containers (like a sidecar), but here we have just one.
      containers:
          # ➡️ The name of the container inside the pod.
          # This name is used internally and for logs, monitoring, etc.
        - name: kubernetes-learning-container

          # ✅ Mount ConfigMap as file inside container
          volumeMounts:
            - name: cfg
              mountPath: /config

          # ➡️ The Docker image to use.
          # Here, it's a local image you’ve built with:
          # docker build -t kubernetes-learning:local .
          #
          #⚠️ If you used a public image or ECR image, this would be something like:
          # image: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/kubernetes-learning:latest
          image: kubernetes-learning:latest
          # This tells Kubernetes: “Don’t try to pull this image from Docker Hub or any registry; just use the local image inside Minikube.”
          imagePullPolicy: Never
          # ➡️ This tells Kubernetes:
          #
          # “My application inside the container listens on port 8080.”
          # It doesn’t expose this to the outside — it just tells Kubernetes how to route traffic inside the pod.
          # You need a Service object to expose this port outside the pod (you already have one in service.yaml).
          ports:
            - containerPort: 8080

          # ----------------- probes -----------------
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
              httpGet:
                path: /actuator/health/readiness
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 5

          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"

          # ✅ Inject config from ConfigMap and Secret
          envFrom:
            - configMapRef:
                name: kube-learning-config
            - secretRef:
                name: kube-learning-secret




# ✅ Summary (Plain English)
#“Run 2 pods of my Spring Boot app using the Docker image kubernetes-learning:local, each listening on port 8080.
# Label them as app: kubernetes-learning so I can control them. If a pod crashes, restart it. If I update the image, roll out the new version gradually.”