apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-learning-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kubernetes-learning-sa
    namespace: default
roleRef:
  kind: Role
  name: kubernetes-learning-role
  apiGroup: rbac.authorization.k8s.io
